### ISSUE TITLE
Implement secure login logics

### ISSUE THREAD

**Issue by goldami1** [goldami1/GraduationProject#20]
Implement secure login logics (library manages 
user's credentials encrypted).

Usecases:
* No valid accesstoken located -> Login screen is shown Immediately.
* Valid accesstoken located -> Loading screen shown until minimal data for main pages is available.
* Valid accesstoken located -> No login screen, however, directly transferred to main page.

**Comment by goldami1** [comment]
After discussion, by @gil-ronen  - implementation would be done by the following meeting (on 03/05)

**Comment by goldami1** [comment]
Following discussion with @gil-ronen , I'll help to implement mentioned feature.

**Comment by gil-ronen** [comment]
Done.
just need to fix the logout button at settings page.
@goldami1
