### ISSUE TITLE
Performance adjustments (mainly break down into threads)

### ISSUE THREAD

**Issue by NadavRamot** [goldami1/GraduationProject#30]

**Comment by goldami1** [comment]
@NadavRamot 
###Multithreading/Step1### - Devided operations on login screen to work on multiple threads. This provides better app-responsibility, and more importantly - true indication of loading state. (while beforehand the loading was only animated)

**Comment by goldami1** [comment]
All relevant code for multithreading is multithreaded. Thus, closing this issue for now.
